### PR TITLE
Tray: Add more buttons

### PR DESCRIPTION
**Pull request by TheKodeToad**
debatable whether they are needed, I think they would be useful

### CODE REVIEW

**Comment by Vendicated** [comment]
this is a good idea and in fact I actually also planned adding them here!

maybe also add "Update Vencord" from the menu

**Comment by TheKodeToad** [comment]
I didn't add the Force Update option as that seems like something you wouldn't need often.

**Comment by Vendicated** [comment]
that option is for when Vencord breaks as a fallback so I think it'd be good to have down there, Discord does too

**Comment by Vendicated** [comment]
that option is for when Vencord breaks as a fallback so I think it'd be good to have down there, Discord does too

**Comment by TheKodeToad** [comment]
Done now!

**Comment by Vendicated** [comment]
thank you!!

**Pull request merged**
