### PR TITLE
Add ScreenSharing

### LINKED ISSUE #1: [Feature Request] Streaming
Streaming is unavailable for some reason

### PR DESCRIPTION
**Pull request by Vendicated**
Not finished or particularly pretty yet but already functional!

This will close #1 

image

https://user-images.githubusercontent.com/45497981/232254273-27a4fa91-f73c-4b0f-9693-e62755a3935c.mp4

### CODE REVIEW

**Comment by TeaSpillStudios** [comment]
This looks awesome. Is there any further work that needs to be done on this and is there an ETA on when it will be merged?

**Comment by Vendicated** [comment]
> This looks awesome. Is there any further work that needs to be done on this and is there an ETA on when it will be merged?

Yes, there is. Currently, it uses ur entire system audio (including discord), which means viewers can hear themselves in your stream. Additionally, currently it's not possible to customise resolution & fps. And the ui also needs to be improved

**Comment by TeaSpillStudios** [comment]
Alright, thanks for answering!

**Comment by Vendicated** [comment]
> > Yes, there is. Currently, it uses ur entire system audio (including discord), which means viewers can hear themselves in your stream.
> 
> Are you guys planning to fix this or is there a roadblock in the way that prevents this from working?

"ETA is whenever it's done :P No idea, whenever I find time & motivation to work on it"

**Comment by ardishco-the-great** [comment]
> > > Yes, there is. Currently, it uses ur entire system audio (including discord), which means viewers can hear themselves in your stream.
> > 
> > 
> > Are you guys planning to fix this or is there a roadblock in the way that prevents this from working?
> 
> "ETA is whenever it's done :P No idea, whenever I find time & motivation to work on it"

Fair enough, I wasn't trying to ask about an ETA but that's still a fair enough answer..

**Comment by ELHIFFROST** [comment]
so, when is a BETA going to be available?

**Comment by enderpuff** [comment]
Will this work on linux? It would be great if you guys could do that, as not even the official client seems to work right now, and i have to use a separate client to make screen sharing work at all (discord-screenaudio)

**Comment by ardishco-the-great** [comment]
> Will this work on linux? It would be great if you guys could do that, as not even the official client seems to work right now, and i have to use a separate client to make screen sharing work at all (discord-screenaudio)

I second this. That's why I asked about Wayland screensharing and audio.

**Comment by Vendicated** [comment]
It just uses electron's screenshare api. It either works or doesn't work. If it doesn't work, I won't go an extra mile to somehow fix it as there are multiple other projects that focus on this already

**Comment by ardishco-the-great** [comment]
Tried on Wayland, does not work. This is basically a "won't fix" type of deal so Wayland users are taking another L today. May god bless pipewire screensharing.

**Comment by ardishco-the-great** [comment]
>  there are multiple other projects that focus on this already

Well, yes, you are right but I think I speak for the most of us when I say that most people aren't a big fan of having another Discord client open just to screenshare properly.

**Pull request merged**
